'use client';

import React, { useState, useEffect } from 'react';
import type { Business, Customer, DailyTally, CreditRecord, Repayment } from '@/domain/types';
import { db } from '@/data/db';
import { getAllTallies } from '@/data/repositories/dailyTallyRepo';
import { getCreditRecordsForBusiness } from '@/data/repositories/creditRecordRepo';
import { getAllRepaymentsForBusiness } from '@/data/repositories/repaymentRepo';
import { getCustomers } from '@/data/repositories/customerRepo';
import {
  todayISO,
  yearMonthOf,
  yearOf,
  formatNaira,
  formatDate,
  creditSalesForDate,
  totalSalesForDay,
  outstanding,
} from '@/domain/derivations';
import { generateCSV, downloadCSV } from '@/domain/export';

interface Props {
  business: Business;
  onBack: () => void;
}

export default function ExportScreen({ business, onBack }: Props) {
  const [period, setPeriod] = useState<'month' | 'year' | 'all'>('month');
  const [isLoading, setIsLoading] = useState(true);
  const [tallies, setTallies] = useState<DailyTally[]>([]);
  const [creditRecords, setCreditRecords] = useState<CreditRecord[]>([]);
  const [repayments, setRepayments] = useState<Repayment[]>([]);
  const [customers, setCustomers] = useState<Customer[]>([]);
  const [toastMessage, setToastMessage] = useState<string | null>(null);

  const today = todayISO();
  const currentYM = yearMonthOf(today);
  const currentYear = yearOf(today);

  // Load data for the business
  useEffect(() => {
    async function loadData() {
      setIsLoading(true);
      try {
        const [allT, allC, allCust] = await Promise.all([
          getAllTallies(business.client_id),
          getCreditRecordsForBusiness(business.client_id),
          getCustomers(business.client_id),
        ]);
        const creditClientIds = allC.map((c) => c.client_id);
        const allR = await getAllRepaymentsForBusiness(creditClientIds);

        setTallies(allT);
        setCreditRecords(allC);
        setCustomers(allCust);
        setRepayments(allR);
      } catch (err) {
        console.error('Failed to load records for export:', err);
      } finally {
        setIsLoading(false);
      }
    }
    loadData();
  }, [business.client_id]);

  // Filter records based on selected period
  const filteredTallies = tallies.filter((t) => {
    if (period === 'month') return t.date.startsWith(currentYM);
    if (period === 'year') return t.date.startsWith(currentYear);
    return true;
  });

  const filteredCredits = creditRecords.filter((c) => {
    if (period === 'month') return c.issued_date.startsWith(currentYM);
    if (period === 'year') return c.issued_date.startsWith(currentYear);
    return true;
  });

  // Calculate summary figures
  const totalCashSales = filteredTallies.reduce((sum, t) => sum + t.cash_sales, 0);
  const totalCreditSales = filteredCredits.reduce((sum, c) => sum + c.amount, 0);
  const totalRevenue = totalCashSales + totalCreditSales;
  const totalExpenses = filteredTallies.reduce((sum, t) => sum + t.expenses, 0);
  const netResult = totalRevenue - totalExpenses;

  // Total outstanding across all credits in system
  const totalOutstanding = creditRecords.reduce((sum, c) => sum + outstanding(c, repayments), 0);

  const handleDownloadCSV = () => {
    const csv = generateCSV({
      business,
      period,
      tallies: filteredTallies,
      creditRecords: filteredCredits,
      repayments,
      customers,
    });
    const filename = `bizpulse-${business.name.toLowerCase().replace(/[^a-z0-9]/g, '_')}-${period}-${today}.csv`;
    downloadCSV(filename, csv);

    setToastMessage('CSV Statement downloaded successfully!');
    setTimeout(() => setToastMessage(null), 3500);
  };

  const handlePrint = () => {
    window.print();
  };

  const handleCopySummary = () => {
    const periodLabel = period === 'month' ? `Month of ${currentYM}` : period === 'year' ? `Year ${currentYear}` : 'All Time';
    const text = `📊 BIZPULSE FINANCIAL SUMMARY\n` +
      `Business: ${business.name} (${business.type})\n` +
      `Period: ${periodLabel}\n` +
      `---------------------------------\n` +
      `• Total Revenue: ${formatNaira(totalRevenue)}\n` +
      `  - Cash Sales: ${formatNaira(totalCashSales)}\n` +
      `  - Credit Sales: ${formatNaira(totalCreditSales)}\n` +
      `• Total Expenses: ${formatNaira(totalExpenses)}\n` +
      `• Net Business Result: ${formatNaira(netResult)} (${netResult >= 0 ? 'Profit' : 'Deficit'})\n` +
      `• Current Outstanding Debt: ${formatNaira(totalOutstanding)}\n` +
      `---------------------------------\n` +
      `Generated by BizPulse — Digital Daily Tally`;

    navigator.clipboard.writeText(text).then(() => {
      setToastMessage('Summary copied to clipboard!');
      setTimeout(() => setToastMessage(null), 3000);
    }).catch(() => {
      setToastMessage('Could not copy to clipboard.');
      setTimeout(() => setToastMessage(null), 3000);
    });
  };

  return (
    <div className="page fade-in" style={{ padding: '20px 20px 80px' }}>
      {/* Header */}
      <div className="flex items-center justify-between" style={{ marginBottom: 20 }}>
        <button
          type="button"
          className="btn btn--ghost btn--sm"
          onClick={onBack}
          style={{ padding: '6px 12px', fontSize: '0.875rem' }}
        >
          ← Back to Dashboard
        </button>
        <span className="badge badge--paid">Lender-Ready</span>
      </div>

      <div style={{ marginBottom: 20 }}>
        <h1 style={{ fontSize: '1.5rem', marginBottom: 4 }}>Statement &amp; Export</h1>
        <p className="text-xs text-muted">
          Download spreadsheets or print verified summaries for lenders and loan applications.
        </p>
      </div>

      {/* Period Selection */}
      <div className="card" style={{ marginBottom: 16 }}>
        <div className="text-xs text-muted font-semibold uppercase tracking-wider mb-2">
          Select Statement Period
        </div>
        <div className="flex gap-2">
          <button
            type="button"
            className={`btn btn--sm flex-1 ${period === 'month' ? 'btn--primary' : 'btn--secondary'}`}
            onClick={() => setPeriod('month')}
            style={{ fontSize: '0.8125rem', padding: '8px' }}
          >
            This Month
          </button>
          <button
            type="button"
            className={`btn btn--sm flex-1 ${period === 'year' ? 'btn--primary' : 'btn--secondary'}`}
            onClick={() => setPeriod('year')}
            style={{ fontSize: '0.8125rem', padding: '8px' }}
          >
            This Year
          </button>
          <button
            type="button"
            className={`btn btn--sm flex-1 ${period === 'all' ? 'btn--primary' : 'btn--secondary'}`}
            onClick={() => setPeriod('all')}
            style={{ fontSize: '0.8125rem', padding: '8px' }}
          >
            All Time
          </button>
        </div>
      </div>

      {isLoading ? (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
          <div className="skeleton" style={{ height: 160, borderRadius: 'var(--radius-lg)' }} />
          <div className="skeleton" style={{ height: 180, borderRadius: 'var(--radius-lg)' }} />
        </div>
      ) : (
        <>
          {/* Printable Lender Summary Card */}
          <div
            className="card card--elevated print-statement"
            style={{
              padding: 20,
              background: 'linear-gradient(160deg, rgba(30,41,59,0.7), rgba(15,23,42,0.9))',
              borderColor: 'rgba(16,185,129,0.3)',
              marginBottom: 16,
            }}
          >
            <div className="flex justify-between items-start" style={{ borderBottom: '1px solid var(--color-border)', paddingBottom: 12, marginBottom: 16 }}>
              <div>
                <h2 style={{ fontSize: '1.25rem', fontWeight: 700, color: 'var(--color-text-primary)' }}>
                  {business.name}
                </h2>
                <p className="text-xs text-muted">
                  Type: {business.type || 'Small Business / Trading'} • Currency: NGN (₦)
                </p>
              </div>
              <div style={{ textAlign: 'right' }}>
                <span className="badge badge--partial" style={{ fontSize: '0.7rem' }}>
                  {period === 'month' ? 'Monthly Statement' : period === 'year' ? 'Annual Statement' : 'Full Ledger'}
                </span>
                <p className="text-xs text-muted" style={{ marginTop: 4 }}>
                  Date: {formatDate(today)}
                </p>
              </div>
            </div>

            {/* Figures Grid */}
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: 12, marginBottom: 16 }}>
              <div style={{ background: 'var(--color-surface-overlay)', padding: '10px 12px', borderRadius: 8 }}>
                <div className="text-xs text-muted">Total Revenue</div>
                <div className="font-bold text-emerald" style={{ fontSize: '1.125rem' }}>
                  {formatNaira(totalRevenue)}
                </div>
                <div className="text-xs text-muted" style={{ fontSize: '0.7rem' }}>
                  Cash: {formatNaira(totalCashSales)} | Credit: {formatNaira(totalCreditSales)}
                </div>
              </div>

              <div style={{ background: 'var(--color-surface-overlay)', padding: '10px 12px', borderRadius: 8 }}>
                <div className="text-xs text-muted">Total Expenses</div>
                <div className="font-bold text-rose" style={{ fontSize: '1.125rem' }}>
                  {formatNaira(totalExpenses)}
                </div>
                <div className="text-xs text-muted" style={{ fontSize: '0.7rem' }}>
                  Operating costs
                </div>
              </div>

              <div style={{ background: 'var(--color-surface-overlay)', padding: '10px 12px', borderRadius: 8 }}>
                <div className="text-xs text-muted">Net Business Result</div>
                <div
                  className="font-bold"
                  style={{
                    fontSize: '1.125rem',
                    color: netResult >= 0 ? 'var(--color-emerald-light)' : 'var(--color-rose)',
                  }}
                >
                  {formatNaira(netResult)}
                </div>
                <div className="text-xs text-muted" style={{ fontSize: '0.7rem' }}>
                  {netResult >= 0 ? 'Operating Profit' : 'Operating Deficit'}
                </div>
              </div>

              <div style={{ background: 'var(--color-surface-overlay)', padding: '10px 12px', borderRadius: 8 }}>
                <div className="text-xs text-muted">Receivables (Owed)</div>
                <div className="font-bold text-amber" style={{ fontSize: '1.125rem' }}>
                  {formatNaira(totalOutstanding)}
                </div>
                <div className="text-xs text-muted" style={{ fontSize: '0.7rem' }}>
                  Recoverable customer debt
                </div>
              </div>
            </div>

            <div style={{ padding: '8px 12px', background: 'rgba(16,185,129,0.06)', borderRadius: 6, border: '1px solid rgba(16,185,129,0.15)' }}>
              <p className="text-xs text-muted" style={{ lineHeight: 1.4 }}>
                🔒 <strong>Verified Ledger:</strong> Based on {filteredTallies.length} daily tallies and {filteredCredits.length} credit transactions recorded in BizPulse.
              </p>
            </div>
          </div>

          {/* Action Buttons */}
          <div className="flex flex-col gap-2">
            <button
              type="button"
              className="btn btn--primary w-full"
              onClick={handleDownloadCSV}
              style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8, padding: 14 }}
            >
              📥 Download CSV Spreadsheet
            </button>

            <div className="flex gap-2">
              <button
                type="button"
                className="btn btn--secondary flex-1"
                onClick={handlePrint}
                style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 6, padding: 12, fontSize: '0.875rem' }}
              >
                🖨️ Print / Save PDF
              </button>

              <button
                type="button"
                className="btn btn--secondary flex-1"
                onClick={handleCopySummary}
                style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 6, padding: 12, fontSize: '0.875rem' }}
              >
                📋 Copy for WhatsApp
              </button>
            </div>
          </div>
        </>
      )}

      {/* Toast Notification */}
      {toastMessage && (
        <div
          className="toast toast--success"
          style={{
            position: 'fixed',
            bottom: 84,
            left: '50%',
            transform: 'translateX(-50%)',
            zIndex: 9999,
          }}
        >
          {toastMessage}
        </div>
      )}
    </div>
  );
}
