import { Suspense } from "react";
import VerifyEmailScreen from "@/ui/screens/VerifyEmailScreen";

export const metadata = {
  title: "Verify Email — BizPulse",
};

// This route handles email-change verification links generated by the backend
// at /verify_email?token=<token>.
export default function VerifyEmailAliasPage() {
  return (
    <Suspense>
      <VerifyEmailScreen />
    </Suspense>
  );
}
